version: '3.8'

services:
  # 1. Database Service
  # Both microservices will connect to this single database container.
  database:
    image: 'mysql:8.0'
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=brief_db # Single, shared database schema.
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - microservice-net

  # 2. Skill Microservice
  skill-service:
    build:
      context: ./skill-service # Path to the skill-service's Dockerfile
    container_name: skill-service
    ports:
      - "8083:8083"
    depends_on:
      - database
    environment:
      # These environment variables will override your application.properties
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/brief_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - microservice-net

  # 3. Brief Microservice
  brief-service:
    build:
      context: ./brief-service # Path to the brief-service's Dockerfile
    container_name: brief-service
    ports:
      - "8081:8081"
    depends_on:
      - database
      - skill-service # Ensures skill-service is healthy before brief-service starts
    environment:
      # Overrides for brief-service
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/brief_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      # This is the correct URL for communicating from brief-service to skill-service
      - SKILL_SERVICE_URL=http://skill-service:8083
    networks:
      - microservice-net

# A named volume to keep your database data even if the container is removed
volumes:
  db-data:

# A dedicated network for our services to communicate through
networks:
  microservice-net:
    driver: bridge