pipeline {
	// run on any machine
    agent any

    tools {
		// tools needs in build
        jdk 'jdk17'
        maven 'maven3'
    }

    stages {
		// get code from github
        stage('Checkout Code') {
			steps {
				echo 'Checking out code...'
                checkout scm
            }
        }

        stage('Build user-service') {
			steps {
				// ensure the build runs from the correct project root
                dir('enaa-skills-backend') {
					echo "--- Building inside: "

                    // build the app
                    bat 'mvn -f user-service/pom.xml clean package -DskipTests'
                }
            }
        }

        stage('Archive Artifact') {
			steps {
				// find the built .jar file
                echo 'Archiving the artifact...'
                archiveArtifacts artifacts: 'enaa-skills-backend/user-service/target/*.jar', fingerprint: true
            }
        }
    }
}