pipeline {
    // comment for testing webhoook2
    agent any // run on any machine

    def appImage

    tools {
        // softwares needs in build
        jdk 'jdk17'
        maven 'maven3'
    }

    stages {
        stage('Checkout Code') {
            steps {
                // download code from git Repo
                echo 'Checking out code...'
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                // run command tools compile
                echo 'Building the brief-service application...'
                dir('brief-service') {
                    // fixes the "Permission denied" error
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Archive Artifact') {
            steps {
                // find the built .jar file
                echo 'Archiving the artifact...'
                archiveArtifacts artifacts: 'brief-service/target/*.jar', fingerprint: true
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building the Docker image...'
                // build image using Dockerfile in the 'brief-service' directory
                script {
                    appImage = docker.build('lahcen404/brief-service', 'brief-service')
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                echo 'Pushing the Docker image...'
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-credentials') {
                        appImage.push("${env.BUILD_NUMBER}")
                        appImage.push("latest")
                    }
                }
            }
        }
    }
}