pipeline {
	agent any // run on any machine

    tools {
		// softwares needs in build
        jdk 'jdk17'
        maven 'maven3'
    }

    stages {
		stage('Checkout Code') {
			steps {
				// download code from git Repo
                echo 'Checking out code...'
                checkout scm
            }
        }
        stage('Build & Test') {
			steps {
				// run command tools compile

             echo 'Building the brief-service application...'
                dir('brief-service') {
					// fixes the "Permission denied" error
                    sh 'chmod +x mvnw'
                    sh './mvnw clean package -DskipTests'
                }
            }
        }

        stage('Archive Artifact') {
			steps {
				// find the built .jar file
                echo 'Archiving the artifact...'
                archiveArtifacts artifacts: 'brief-service/target/*.jar', fingerprint: true
            }
        }
    }
}