services:
  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=briefdb
    ports:
      - "3307:3306"

  brief-service:
    build:
      context: .
    ports:
      - "8081:8080"
    environment:
      # --- DATABASE CONNECTION ---
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/briefdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      # --- DISABLE EUREKA ---
      - EUREKA_CLIENT_ENABLED=false
    depends_on:
      - mysql-db