pipeline {
    // comment for testing webhoook2
    agent any // run on any machine

    tools {
        // softwares needs in build
        jdk 'jdk17'
        maven 'maven3'
    }

    stages {
        stage('Checkout Code') {
            steps {
                // download code from git Repo
                echo 'Checking out code...'
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                // run command tools compile
             echo 'Building the brief-service application...'

             // Grant execute permission to mvnw located at the root
             sh 'chmod +x mvnw'

             // Run mvnw from the root, but specify the pom.xml for the brief-service module
             // The -f flag tells Maven which POM file to use.
             sh './mvnw -f brief-service/pom.xml clean package -DskipTests'
            }
        }

        stage('Archive Artifact') {
            steps {
                // find the built .jar file
                echo 'Archiving the artifact...'
                // This path is correct because it's relative to the workspace root
                archiveArtifacts artifacts: 'brief-service/target/*.jar', fingerprint: true
            }
        }
    }
}